name       : wxsvg
version    : 1.5.16
release    : 1
source     :
    - https://sourceforge.net/projects/wxsvg/files/wxsvg/1.5.16/wxsvg-1.5.16.tar.bz2 : a4bdd3ebc3a32add577bc5414d811b93e1642910d9fa41623c72ee71a696cabe
license    : GPL-2.0-or-later
component  : multimedia.library
summary    : Library to create, manipulate and render SVG files
description: |
    wxSVG is C++ library to create, manipulate and render Scalable Vector Graphics (SVG) files with the wxWidgets toolkit.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(libavformat)
    - pkgconfig(libexif)
    - pkgconfig(pango)
    - wxwidgets-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
