name       : wxsvg
version    : 1.5.24
release    : 2
source     :
    - https://sourceforge.net/projects/wxsvg/files/wxsvg/1.5.24/wxsvg-1.5.24.tar.bz2 : ae473291f8d0a5feafa06cd270c826c6bead4bceb2b9dd6fcecf2db7c25e2482
license    : GPL-2.0-or-later
component  : multimedia.library
summary    : Library to create, manipulate and render SVG files
description: |
    wxSVG is C++ library to create, manipulate and render Scalable Vector Graphics (SVG) files with the wxWidgets toolkit.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(libavformat)
    - pkgconfig(libexif)
    - pkgconfig(pango)
    - wxwidgets-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
